SET IDENTITY_INSERT [System].[LogLevel] ON 
INSERT [System].[LogLevel] ([Id], [Title], [TitleEn]) VALUES (1, N'کامل', 'Verbose')
INSERT [System].[LogLevel] ([Id], [Title], [TitleEn]) VALUES (2, N'اطلاعاتی', 'Information')
INSERT [System].[LogLevel] ([Id], [Title], [TitleEn]) VALUES (3, N'هشدار', 'Warning')
INSERT [System].[LogLevel] ([Id], [Title], [TitleEn]) VALUES (4, N'خطا', 'Error')
SET IDENTITY_INSERT [System].[LogLevel] OFF
